### ISSUE TITLE
License

### ISSUE THREAD

**Issue by iamale** [foobar64/pykotletki#7]
We need a license. I suggest something like AGPL, but for burgers.

**Comment by foobar64** [comment]
Let's rewrite the Beerware license to Kotletkaware license.

**Comment by foobar64** [comment]
/*
 * ----------------------------------------------------------------------------
 * "THE KOTLETKA-WARE LICENSE" (Revision 42):
 * <mail@Foobar64.ME> wrote this file.  As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy me a kotletka in return.   foobar64
 * ----------------------------------------------------------------------------
 */

**Comment by iamale** [comment]
@foobar64 Эй, а мне? .__.

**Comment by foobar64** [comment]
@iamale Сейчас впишу всех.

**Comment by foobar64** [comment]
@iamale @PeerRails Готово, сейчас запушаю.

**Comment by foobar64** [comment]
Closed by e4178b73362f908e0199a5b6c6f7a5dd561d4912.

**Comment by foobar64** [comment]
Чего-то адреса не отображаются.
